### Matrix Multiplication

In [22]:
import numpy as np
from numpy import linalg

m1 = np.random.randn(3,5)
print(m1)
m2 = np.eye(5)
print(m2)
print('m1.dot(m2)\n', m1.dot(m2))
print('m1@m2\n', m1@m2)


[[-0.26783211 -1.08446038 -0.53335337  1.47878265 -0.15374837]
 [ 0.71990766  0.97389959 -0.61136397 -0.54030236 -1.99129911]
 [-0.68342048 -1.21106442  1.23440805  0.37429582 -0.75526029]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
m1.dot(m2)
 [[-0.26783211 -1.08446038 -0.53335337  1.47878265 -0.15374837]
 [ 0.71990766  0.97389959 -0.61136397 -0.54030236 -1.99129911]
 [-0.68342048 -1.21106442  1.23440805  0.37429582 -0.75526029]]
m1@m2
 [[-0.26783211 -1.08446038 -0.53335337  1.47878265 -0.15374837]
 [ 0.71990766  0.97389959 -0.61136397 -0.54030236 -1.99129911]
 [-0.68342048 -1.21106442  1.23440805  0.37429582 -0.75526029]]


In [23]:
m1 = np.random.randn(4,4)
print(m1@linalg.inv(m1))

[[ 1.00000000e+00 -3.46944695e-17 -2.77555756e-17 -1.38777878e-17]
 [ 1.11022302e-16  1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00 -5.55111512e-17]
 [-2.22044605e-16 -2.22044605e-16  1.11022302e-16  1.00000000e+00]]
