### Vectorization
Performing array operation with out loops

In [7]:
import numpy as np
odd = np.arange(1,11, 2)
even = np.arange(0, 11, 2)
#### if we need to perform operation between all pairs of element from odd and even
#### then 'np.meshgrid' will create two matrixes such that permorming element wise operation
#### will yeild operation for all possible pairs of element from odd and even
#### 1st array will be repeated as rows of 1st matrix and 2nd array will be repeated as column of 2nd matrix
xs, ys = np.meshgrid(odd, even)
distances = np.sqrt(xs**2 + ys**2)
print (xs)
print(ys)
print(distances)

[[1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]]
[[ 0  0  0  0  0]
 [ 2  2  2  2  2]
 [ 4  4  4  4  4]
 [ 6  6  6  6  6]
 [ 8  8  8  8  8]
 [10 10 10 10 10]]
[[ 1.          3.          5.          7.          9.        ]
 [ 2.23606798  3.60555128  5.38516481  7.28010989  9.21954446]
 [ 4.12310563  5.          6.40312424  8.06225775  9.8488578 ]
 [ 6.08276253  6.70820393  7.81024968  9.21954446 10.81665383]
 [ 8.06225775  8.54400375  9.43398113 10.63014581 12.04159458]
 [10.04987562 10.44030651 11.18033989 12.20655562 13.45362405]]


### np.where
logical trinery operation for arrays.
- param1: array of condition
- param2: scalar or array from which value is taken if corresponding value in condition is true
- param3: scalar or array


In [24]:
arr = np.random.randn(10).reshape(2,5)
print(arr)
### replace all -ve numbers with -2 and all positive with 2
arr2 = np.where(arr>0, 2, -2)
print(arr2)
### replace all -ve numbers with 0 and take positive number at it is
arr3 = np.where(arr>0, arr, 0)
print(arr3)

[[-0.61936563  0.35693356  1.05831575 -0.86951069 -0.58189523]
 [ 0.97201507  0.44622398 -0.26541524 -0.27446162 -1.39663287]]
[[-2  2  2 -2 -2]
 [ 2  2 -2 -2 -2]]
[[0.         0.35693356 1.05831575 0.         0.        ]
 [0.97201507 0.44622398 0.         0.         0.        ]]


### Aggregate or Reduce Functions

In [43]:
arr = np.arange(12).reshape(3,4)
print(arr)
print('np.sum(arr)', np.sum(arr))
print('arr.mean()', arr.mean())
print('arr.sum(axis=0)', arr.sum(axis=0))

print('Cumulative sum: arr.cumsum()\n',arr.cumsum())
print('Cumulative sum: arr.cumsum(axis=1)\n',arr.cumsum(axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
np.sum(arr) 66
arr.mean() 5.5
arr.sum(axis=0) [12 15 18 21]
Cumulative sum: arr.cumsum()
 [ 0  1  3  6 10 15 21 28 36 45 55 66]
Cumulative sum: arr.cumsum(axis=1)
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


### Boolean Array

In [52]:
bool_arr = np.random.choice([0,1], (3,4))
print(bool_arr)
print(bool_arr.any()) ## If any element is true or non zero
print(bool_arr.all()) ## If all element are treu or non zero

[[1 0 0 1]
 [0 0 1 0]
 [1 0 0 1]]
True
False


### Sorting

In [65]:
arr = np.random.choice(range(15), (3,4))

print(arr)
print(np.sort(arr)) # sort array in copy
arr.sort(axis=0) # sorts the array in place
print(arr)


[[13  6 13  1]
 [12 13 14  3]
 [11  1  8  0]]
[[ 1  6 13 13]
 [ 3 12 13 14]
 [ 0  1  8 11]]
[[11  1  8  0]
 [12  6 13  1]
 [13 13 14  3]]
