### 1D Array

In [33]:
import numpy as np
arr_1d = np.array(range(10))
slice_1d = arr_1d[4:8] ## similar to python list
print('arr_1d[4:8]\n', slice_1d)
slice_1d[:] = 42 ## scalar value can be assigned to range. change in slice will reflect to original array
print('changed slice\n', arr_1d)

arr_1d[4:8]
 [4 5 6 7]
changed slice
 [ 0  1  2  3 42 42 42 42  8  9]


### Copy range

In [34]:
import numpy as np
arr_1d = np.array(range(10))
copy_slice = arr_1d[3:8].copy() ## to make copy we need explicitly call copy
copy_slice[2:4] = 0
print('arr_ld:', arr_1d)
print('copy_slice', copy_slice)

arr_ld: [0 1 2 3 4 5 6 7 8 9]
copy_slice [3 4 0 0 7]


### ND array
- If arry3D is a 3D array arry3D[0,2,2] will give us scalar value
- We can think of 2D array as list of 1D array, 3D array as list of 2D array, 4D array as list of 3D array and so on.
- If we omit last 2 indexes, like arry3D[0], we'll get 0th item in list of 2D array
- If we omit the last index, like arry3D[0,2], we'll get 1D array, which will be item at index 2 in list of 1D array within 0th item in list of 2D array



In [35]:
import numpy as np
start_value = 0

def create_lst_of_scalar(size):
    'returns list of scalar which is a 1D list'
    global start_value
    lst = list(range(start_value, start_value + size))
    start_value += size
    return lst

def create_lst_of_1d_lst(shape):
    'returns list of 1D list which is a 2D list'
    return [create_lst_of_scalar(shape[1]) for _ in range(shape[0])]

def create_lst_of_2d_lst(shape):
    'returns list of 2D list which is a 3D list'
    return [create_lst_of_1d_lst(shape[1:3]) for _ in range(shape[0])]


arr3d = np.array(create_lst_of_2d_lst((3,4,5)))
print('arr3d\n', arr3d)
print('arr3d[1]\n', arr3d[1])
print('arr3d[1,2]\n', arr3d[1,2])
print('arr3d[1,2,2]\n', arr3d[1,2,2])


arr3d
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
arr3d[1]
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
arr3d[1,2]
 [30 31 32 33 34]
arr3d[1,2,2]
 32


### Slice ND Array

In [36]:
arr3d = np.array(create_lst_of_2d_lst((3,4,5)))
### this slice will get all items from list of 2D array, 1:3 (position 1 and 2) from list of 1D array and 2:4 item from array
slice1 = arr3d[:,1:3,2:4]
print('arr3d\n', arr3d)
print('arr3d[:,1:3,2:4]\n', slice1)
slice1[:] = 0
print('arr3d[:,1:3,2:4]=0\n', arr3d)

arr3d
 [[[ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]
  [ 75  76  77  78  79]]

 [[ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]]
arr3d[:,1:3,2:4]
 [[[ 67  68]
  [ 72  73]]

 [[ 87  88]
  [ 92  93]]

 [[107 108]
  [112 113]]]
arr3d[:,1:3,2:4]=0
 [[[ 60  61  62  63  64]
  [ 65  66   0   0  69]
  [ 70  71   0   0  74]
  [ 75  76  77  78  79]]

 [[ 80  81  82  83  84]
  [ 85  86   0   0  89]
  [ 90  91   0   0  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106   0   0 109]
  [110 111   0   0 114]
  [115 116 117 118 119]]]


### Boolean Indexing
Boolean indexing will always create copy

In [37]:
import numpy as np
np.random.seed(5)
arr = np.random.randn(3,3,4)
is_positive = arr>=0
print('arr\n', arr)
print('is_positive\n', is_positive)

positive_items = arr[is_positive]
negetive_items = arr[~is_positive]
print('positive_items\n', positive_items)
print('negetive items\n', negetive_items)
arr[~is_positive]=0 # make negative items zero
print('Replaced -ve items with 0\n', arr)


arr
 [[[ 0.44122749 -0.33087015  2.43077119 -0.25209213]
  [ 0.10960984  1.58248112 -0.9092324  -0.59163666]
  [ 0.18760323 -0.32986996 -1.19276461 -0.20487651]]

 [[-0.35882895  0.6034716  -1.66478853 -0.70017904]
  [ 1.15139101  1.85733101 -1.51117956  0.64484751]
  [-0.98060789 -0.85685315 -0.87187918 -0.42250793]]

 [[ 0.99643983  0.71242127  0.05914424 -0.36331088]
  [ 0.00328884 -0.10593044  0.79305332 -0.63157163]
  [-0.00619491 -0.10106761 -0.05230815  0.24921766]]]
is_positive
 [[[ True False  True False]
  [ True  True False False]
  [ True False False False]]

 [[False  True False False]
  [ True  True False  True]
  [False False False False]]

 [[ True  True  True False]
  [ True False  True False]
  [False False False  True]]]
positive_items
 [0.44122749 2.43077119 0.10960984 1.58248112 0.18760323 0.6034716
 1.15139101 1.85733101 0.64484751 0.99643983 0.71242127 0.05914424
 0.00328884 0.79305332 0.24921766]
negetive items
 [-0.33087015 -0.25209213 -0.9092324  -0.59163666 -

### Mixed indexing

In [38]:
users = np.array(['ram', 'shyam', 'ram', 'hari','shyam', 'chari', 'chari', 'pari', ])
scores =  np.random.binomial(100, .4, (8,5))
print("scores\n", scores)
shyam = users == 'shyam'
print('shaym\n', shyam)
shyam_scores = scores[shyam]
print('shyam_scores: scores[shyam]\n', shyam_scores)
print('shyam_scores: scores[shyam, 2:4]\n', scores[shyam, 2:4])


scores
 [[47 40 40 47 48]
 [25 46 40 45 47]
 [29 39 47 47 40]
 [43 48 41 45 46]
 [43 41 38 47 39]
 [36 42 34 31 41]
 [36 40 34 48 36]
 [41 33 43 37 40]]
shaym
 [False  True False False  True False False False]
shyam_scores: scores[shyam]
 [[25 46 40 45 47]
 [43 41 38 47 39]]
shyam_scores: scores[shyam, 2:4]
 [[40 45]
 [38 47]]


### Multi Dimension Boolean Indexing
- boolean indexing returns one dimensional array of items whose index as true in the boolean index
- If dimension of boolean index is less than the indexed array, dimension of matched item will be equal to the difference in dimension. ie. if array is of 3D and index is of 2D then items matched by the index will be 1D array. if index is 1D then items matched will be 2D
- If length of boolean index for any dimension is not equal to length of indexed array in corresponding dimension error will be thrown

In [57]:
arr = np.random.randint(0,100, (3,3,4))
bool_index3D = np.random.randn(3,3,4)>0
bool_index2D = np.random.randn(3,3)>0
bool_index1D = [True, False, True]
print('arr\n', arr)

print('bool_index2D\n', bool_index2D)
print('arr[bool_index3D]\n', arr[bool_index3D])
print('arr[bool_index2D]\n', arr[bool_index2D])
print('arr[bool_index1D]\n', arr[bool_index1D])



arr
 [[[44 96 97 59]
  [95 33 34 31]
  [33 83 96 95]]

 [[24 95 65 14]
  [ 4 35 39 16]
  [86 48 42  3]]

 [[65 32 78 80]
  [ 3 65 23 66]
  [71 48 13 39]]]
bool_index2D
 [[False False False]
 [False  True  True]
 [ True False False]]
arr[bool_index3D]
 [44 96 59 31 96 95 24 65  4 86 48  3 65 78  3 71 48 13]
arr[bool_index2D]
 [[ 4 35 39 16]
 [86 48 42  3]
 [65 32 78 80]]
arr[bool_index1D]
 [[[44 96 97 59]
  [95 33 34 31]
  [33 83 96 95]]

 [[65 32 78 80]
  [ 3 65 23 66]
  [71 48 13 39]]]


### Fancy Indexing
- Indexing by integer array
- If index is [4,1,6,3] array returned will have items at 4th, 1st, 6th and 3rd in that order

In [66]:
arr2D = np.zeros((8,4))
for i in range(8):
    arr2D[i]=i
print('arr2D\n', arr2D)
print('arr2D[[4,1,7]]\n', arr2D[[4,1,7]])

arr
 [[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
arr[[4,1,7]]
 [[4. 4. 4. 4.]
 [1. 1. 1. 1.]
 [7. 7. 7. 7.]]


### Multi dimensional index
- If index integer array is 2D like  [[1,2],[0,1],[3,3]]] then it will find items at (1,0,3) and (2,1,3)
- Index like [[1,2],[0,1,2],[3,3]]] will raise error as list size are not same

In [107]:
arr3D = np.zeros((3,6,4))
for i in range(3):
    for j in range(6):
        for k in range(4):
            arr3D[i,j,k]=i*6+4*j+k
print('arr3D\n', arr3D)
print('arr3D[[1,2]]\n', arr3D[[1,2]])
print('arr3D[]\n', arr3D[[[1,2],[0,3],[3,3]]])


arr3D
 [[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[ 6.  7.  8.  9.]
  [10. 11. 12. 13.]
  [14. 15. 16. 17.]
  [18. 19. 20. 21.]
  [22. 23. 24. 25.]
  [26. 27. 28. 29.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]
  [24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. 33. 34. 35.]]]
arr3D[[1,2]]
 [[[ 6.  7.  8.  9.]
  [10. 11. 12. 13.]
  [14. 15. 16. 17.]
  [18. 19. 20. 21.]
  [22. 23. 24. 25.]
  [26. 27. 28. 29.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]
  [24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. 33. 34. 35.]]]
arr3D[]
 [ 9. 27.]
