### Unary Universal Function (ufunc)
- function that takes and array and perform operation array and return an array (sometimes 2 or more)
- must of these function also have corresponding operator

In [10]:
import numpy as np
arr = np.arange(12).reshape(3,4)
## unary ufunc, eg: sqrt, abs, celi, rint, modf etc
print('np.square(arr)\n', np.square(arr))
new_arr = arr/2
arr_fraction_part, arr_int_part  = np.modf(new_arr)
print('np.modf(new_arr)\n', arr_int_part, '\n\n\n', arr_fraction_part)



np.square(arr)
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
np.modf(new_arr)
 [[0. 0. 1. 1.]
 [2. 2. 3. 3.]
 [4. 4. 5. 5.]] 


 [[0.  0.5 0.  0.5]
 [0.  0.5 0.  0.5]
 [0.  0.5 0.  0.5]]


### Binary ufuncs

In [24]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(8,20).reshape(3,4)
print(arr1, '\n',arr2)
np.mod(arr2,  arr1)
arr2%arr1



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
 [[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[0, 1, 1, 3],
       [2, 1, 0, 7],
       [7, 7, 7, 7]])