### Reshape
Array having 16 elements can be reshaped to 4*4 or 2*4*2 or 2*2*2*2

In [11]:
import numpy as np
arr = np.arange(16).reshape((4,4))
print('reshape((4,4))\n', arr)
arr=arr.reshape((2,4,2))
print('\nreshape((2,4,2))\n',arr)


reshape((4,4))
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

reshape((2,4,2))
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


### Transpose
for 2D array E_ij is transposed to E_ji

In [15]:
arr = np.arange(16).reshape((4,4))
print('arr\n', arr)
print('arr.T\n', arr.T)
print('arr.transpose()\n', arr.transpose())

arr
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
arr.T
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
arr.transpose
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


### 2+D Transpose
- E_ijk is transposed to E_kji
- swapaxes swaps the given index of the array
- For 2+D array we can give how to transpose the index like E_ijk to E_kji or E_jik etc 

In [23]:
arr = np.arange(30).reshape((2,3,5))
print(arr)
print('arr.T\n', arr.T)
print('arr.swapaxes(0,2)\n', arr.swapaxes(0,2)) ## for 3d array it is same as simple transpose
print('arr.tranpose(2,0,1)\nE_ijk to E_kij\n', arr.transpose(2,0,1))


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
arr.T
 [[[ 0 15]
  [ 5 20]
  [10 25]]

 [[ 1 16]
  [ 6 21]
  [11 26]]

 [[ 2 17]
  [ 7 22]
  [12 27]]

 [[ 3 18]
  [ 8 23]
  [13 28]]

 [[ 4 19]
  [ 9 24]
  [14 29]]]
arr.swapaxes(0,2)
 [[[ 0 15]
  [ 5 20]
  [10 25]]

 [[ 1 16]
  [ 6 21]
  [11 26]]

 [[ 2 17]
  [ 7 22]
  [12 27]]

 [[ 3 18]
  [ 8 23]
  [13 28]]

 [[ 4 19]
  [ 9 24]
  [14 29]]]
arr.tranpose(2,0,1)
E_ijk to E_kij
 [[[ 0  5 10]
  [15 20 25]]

 [[ 1  6 11]
  [16 21 26]]

 [[ 2  7 12]
  [17 22 27]]

 [[ 3  8 13]
  [18 23 28]]

 [[ 4  9 14]
  [19 24 29]]]
