### Array Arithmetic

In [14]:
import numpy as np
arr1 = np.random.randint(10, size=(3,10))
print('arr1\n', arr1) 
arr2 = np.random.randint(10, size=(3,10))
print('arr2\n', arr2)

print('arr1*arr2\n', arr1 * arr2) ## arithmetic operation between same shape array perform the operation element wise

arr1
 [[0 8 7 1 2 1 4 6 5 2]
 [6 3 2 8 8 7 3 7 0 2]
 [6 4 7 3 0 3 6 7 4 7]]
arr2
 [[8 6 2 9 6 0 9 6 3 5]
 [3 2 8 8 8 2 4 6 9 4]
 [9 2 1 3 5 4 0 5 4 7]]
arr1*arr2
 [[ 0 48 14  9 12  0 36 36 15 10]
 [18  6 16 64 64 14 12 42  0  8]
 [54  8  7  9  0 12  0 35 16 49]]


### Scalar Operation

In [16]:
print('1/arr1\n', 1/(arr1+1)) # scalar operation is performed in individual element

1/arr1
 [[1.         0.11111111 0.125      0.5        0.33333333 0.5
  0.2        0.14285714 0.16666667 0.33333333]
 [0.14285714 0.25       0.33333333 0.11111111 0.11111111 0.125
  0.25       0.125      1.         0.33333333]
 [0.14285714 0.2        0.125      0.25       1.         0.25
  0.14285714 0.125      0.2        0.125     ]]


### Comparision

In [20]:
print('arr1\n', arr1)
print('arr2\n', arr2)
print('arr1>5\n', arr1>5) ## compares element wise and creates boolean array of same shape as operated array
print('arr1==arr2\n', arr1==arr2)

arr1
 [[0 8 7 1 2 1 4 6 5 2]
 [6 3 2 8 8 7 3 7 0 2]
 [6 4 7 3 0 3 6 7 4 7]]
arr2
 [[8 6 2 9 6 0 9 6 3 5]
 [3 2 8 8 8 2 4 6 9 4]
 [9 2 1 3 5 4 0 5 4 7]]
arr1>5
 [[False  True  True False False False False  True False False]
 [ True False False  True  True  True False  True False False]
 [ True False  True False False False  True  True False  True]]
arr1==arr2
 [[False False False False False False False  True False False]
 [False False False  True  True False False False False False]
 [False False False  True False False False False  True  True]]
