In [19]:
import numpy as np
arr = np.random.choice(range(10), (2,4))
arr2 = np.random.choice(range(10), (2,4))
print(arr)
print('np.unique(arr)', np.unique(arr)) ## find unique elements from array

print('np.in1d(arr, [3,6,4])\n', np.in1d(arr, [3,6,4])) ## check if each element of arr in [3,6,4]
print('np.intersect1d(arr, arr2)\n', np.intersect1d(arr, arr2))
print('np.setxor1d(arr, arr2)\n', np.setxor1d(arr, arr2))

[[7 9 8 6]
 [2 5 0 2]]
np.unique(arr) [0 2 5 6 7 8 9]
np.in1d(arr, [3,6,4])
 [False False False  True False False False False]
np.intersect1d(arr, arr2)
 [0 5 9]
np.setxor1d(arr, arr2)
 [2 3 6 7 8]
